### ISSUE TITLE
feat: exposing exception related metrics

### ISSUE THREAD

**Issue by Abdulsametileri** [Trendyol/kafka-cronsumer#34]

**Comment by emreodabas** [comment]
total_retried_count
total_ignored_count
processed_message_gauge

**Comment by Abdulsametileri** [comment]
We can add example and documentation how to use this collector with kafka-cronsumer (not kafka-konsumer) @oguzyildirim

**Comment by Abdulsametileri** [comment]
Implemented 🚀
