### ISSUE TITLE
feat: add exception message to the kafka header for debugging purposes

### ISSUE THREAD

**Issue by Abdulsametileri** [Trendyol/kafka-cronsumer#55]

**Comment by keremcankabadayi** [comment]
Actually i offered this feature. Glad to here you're already using X-Exception and X-ExceptionAt fields @oguzhaneren 

We return `err` to cronsumer if we want to publish error topic. we have `err`, library can add `X-ErrMessage` to header by default. Client can also add but this library is dealing with error handling. we can expose the error by default :)

**Comment by Abdulsametileri** [comment]
Implemented by @oguzyildirim
