### ISSUE TITLE
Consume message when header has expected value

### ISSUE THREAD

**Issue by emreodabas** [Trendyol/kafka-cronsumer#65]
On the consumer side of Kafka topics, we want to ignore some messages or process only some messages depending on the message type. Mostly, message producers send their events with some details on the message header.  So, could the cronsumer project gives us a feature about ignoring/accepting messages for a given header key/values.

**Comment by emrekosen** [comment]
I was about to try this one but @emreodabas already did 😄  I just have another idea but don't know if would it be performant or a good fit. How about accepting a skip function whose parameter is headers with config and running that function to decide consume or not. With this way, users can run logic on multiple headers and do more. It's something close to middleware functions in fiber.

**Comment by emreodabas** [comment]
Hii, 
This is an unlucky coincidence :) We also discussed it with @Abdulsametileri  and decided to implement it like you said. Let's do this task as a pair. I'll contact you.

**Comment by Abdulsametileri** [comment]
Hi, @emrekosen. Can you give me a deadline? We need to support it as soon as possible. :)

**Comment by emrekosen** [comment]
Hi, @Abdulsametileri sorry for being late. I added an example and updated the readme. PR is ready for review.

**Comment by Abdulsametileri** [comment]
Thank you <3 I added my review to the PR
